name: Meme
favicon: null
layout_spectrum: 0.843369725625962
typography_spectrum: 0.059267371194437146
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.1870076407212764
  lightness: 0.0028508459217846394
  saturation: 0.9133759667165577
  rhythmicContrast: 0.11777293658815324
purpose: []
